# pull official base image
FROM node:16.13.1-alpine
# FROM node:16.13.1-buster

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
#ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install

# EXPOSE 3000

# add app
COPY . ./


CMD [ "npm", "run", "start" ]